name: Build and Package Ferrous

on:
  push:
    branches: [main, master]

permissions: write-all

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Version
        id: version
        uses: motain/onefootball-actions/bump-release@master
        with:
          access_token: ${{ github.token }}
          repository: ${{ github.repository }}
          tag_only: true


      - name: Build
        run: make build
        env:
          VERSION: ${{ steps.version.outputs.new-version}}

      - name: Package
        run: make package
        env:
          VERSION: ${{ steps.version.outputs.new-version}}

      - name: rename
        run: |
          mv dist/ferrous-*.dmg dist/ferrous-${{ steps.version.outputs.new-version}}.dmg
          mv dist/ferrous-*.pkg dist/ferrous-${{ steps.version.outputs.new-version}}.pkg

      - name: Release
        uses: motain/onefootball-actions/bump-release@master
        with:
          access_token: ${{ github.token }}
          repository: ${{ github.repository }}
          version: ${{ steps.version.outputs.new-version}}
          release_only: true
          generate_notes: true
          assets: |
            dist/ferrous-${{ steps.version.outputs.new-version}}.dmg
            dist/ferrous-${{ steps.version.outputs.new-version}}.pkg